### ISSUE TITLE
Move to another host

### ISSUE THREAD

**Issue by mmintel** [mabelisle/GoogleWiz#6]
Hey there!

First thanks for updating this Custom ROM! :)

Trying to download latest version, but it takes 6 hours for me, I guess github is not the best host for large files. Maybe consider switching to another one?

//Update: it crashed after about 1h, after "resume" it says "forbidden".

Cheers

**Comment by mabelisle** [comment]
Where are you located? I could try to find a mirror but I had really good download myself there. 50Mbps+

**Comment by mabelisle** [comment]
Try this: https://mega.nz/#!I1RXyKaJ!fhBQTMPfnwMl0ML_RuNiYFcUyjLE724OSO5rZbGVf6A
